In [1]:
import pandas as pd

df = pd.read_csv("BankChurners.csv")
df.shape


(10127, 23)

In [3]:
df

CLIENTNUM     Attrition_Flag  Customer_Age Gender  Dependent_count  \
0      768805383  Existing Customer            45      M                3   
1      818770008  Existing Customer            49      F                5   
2      713982108  Existing Customer            51      M                3   
3      769911858  Existing Customer            40      F                4   
4      709106358  Existing Customer            40      M                3   
...          ...                ...           ...    ...              ...   
10122  772366833  Existing Customer            50      M                2   
10123  710638233  Attrited Customer            41      M                2   
10124  716506083  Attrited Customer            44      F                1   
10125  717406983  Attrited Customer            30      M                2   
10126  714337233  Attrited Customer            43      F                2   

      Education_Level Marital_Status Income_Category Card_Category  \
0         High School        Married     $60K - $80K          Blue   
1            Graduate         Single  Less than $40K          Blue   
2            Graduate        Married    $80K - $120K          Blue   
3         High School        Unknown  Less than $40K          Blue   
4          Uneducated        Married     $60K - $80K          Blue   
...               ...            ...             ...           ...   
10122        Graduate         Single     $40K - $60K          Blue   
10123         Unknown       Divorced     $40K - $60K          Blue   
10124     High School        Married  Less than $40K          Blue   
10125        Graduate        Unknown     $40K - $60K          Blue   
10126        Graduate        Married  Less than $40K        Silver   

       Months_on_book  ...  Credit_Limit  Total_Revolving_Bal  \
0                  39  ...       12691.0                  777   
1                  44  ...        8256.0                  864   
2                  36  ...        3418.0                    0   
3                  34  ...        3313.0                 2517   
4                  21  ...        4716.0                    0   
...               ...  ...           ...                  ...   
10122              40  ...        4003.0                 1851   
10123              25  ...        4277.0                 2186   
10124              36  ...        5409.0                    0   
10125              36  ...        5281.0                    0   
10126              25  ...       10388.0                 1961   

       Avg_Open_To_Buy  Total_Amt_Chng_Q4_Q1  Total_Trans_Amt  Total_Trans_Ct  \
0              11914.0                 1.335             1144              42   
1               7392.0                 1.541             1291              33   
2               3418.0                 2.594             1887              20   
3                796.0                 1.405             1171              20   
4               4716.0                 2.175              816              28   
...                ...                   ...              ...             ...   
10122           2152.0                 0.703            15476             117   
10123           2091.0                 0.804             8764              69   
10124           5409.0                 0.819            10291              60   
10125           5281.0                 0.535             8395              62   
10126           8427.0                 0.703            10294              61   

       Total_Ct_Chng_Q4_Q1  Avg_Utilization_Ratio  \
0                    1.625                  0.061   
1                    3.714                  0.105   
2                    2.333                  0.000   
3                    2.333                  0.760   
4                    2.500                  0.000   
...                    ...                    ...   
10122                0.857                  0.462   
10123                0.683                  0.511   
10124     

In [5]:
df.columns.tolist()

['CLIENTNUM',
 'Attrition_Flag',
 'Customer_Age',
 'Gender',
 'Dependent_count',
 'Education_Level',
 'Marital_Status',
 'Income_Category',
 'Card_Category',
 'Months_on_book',
 'Total_Relationship_Count',
 'Months_Inactive_12_mon',
 'Contacts_Count_12_mon',
 'Credit_Limit',
 'Total_Revolving_Bal',
 'Avg_Open_To_Buy',
 'Total_Amt_Chng_Q4_Q1',
 'Total_Trans_Amt',
 'Total_Trans_Ct',
 'Total_Ct_Chng_Q4_Q1',
 'Avg_Utilization_Ratio',
 'Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_1',
 'Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_2']

In [7]:
df.head()


CLIENTNUM     Attrition_Flag  Customer_Age Gender  Dependent_count  \
0  768805383  Existing Customer            45      M                3   
1  818770008  Existing Customer            49      F                5   
2  713982108  Existing Customer            51      M                3   
3  769911858  Existing Customer            40      F                4   
4  709106358  Existing Customer            40      M                3   

  Education_Level Marital_Status Income_Category Card_Category  \
0     High School        Married     $60K - $80K          Blue   
1        Graduate         Single  Less than $40K          Blue   
2        Graduate        Married    $80K - $120K          Blue   
3     High School        Unknown  Less than $40K          Blue   
4      Uneducated        Married     $60K - $80K          Blue   

   Months_on_book  ...  Credit_Limit  Total_Revolving_Bal  Avg_Open_To_Buy  \
0              39  ...       12691.0                  777          11914.0   
1              44  ...        8256.0                  864           7392.0   
2              36  ...        3418.0                    0           3418.0   
3              34  ...        3313.0                 2517            796.0   
4              21  ...        4716.0                    0           4716.0   

   Total_Amt_Chng_Q4_Q1  Total_Trans_Amt  Total_Trans_Ct  Total_Ct_Chng_Q4_Q1  \
0                 1.335             1144              42                1.625   
1                 1.541             1291              33                3.714   
2                 2.594             1887              20                2.333   
3                 1.405             1171              20                2.333   
4                 2.175              816              28                2.500   

   Avg_Utilization_Ratio  \
0                  0.061   
1                  0.105   
2                  0.000   
3                  0.760   
4                  0.000   

   Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_1  \
0                                           0.000093                                                                                    
1                                           0.000057                                                                                    
2                                           0.000021                                                                                    
3                                           0.000134                                                                                    
4                                           0.000022                                                                                    

   Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_2  
0                                            0.99991                                                                                   
1                                            0.99994                                                                                   
2                                            0.99998                                                                                   
3                                            0.99987                                                                                   
4                                            0.99998                                                                                   

[5 rows x 23 columns]

In [9]:
df.isnull().sum()

CLIENTNUM                                                                                                                             0
Attrition_Flag                                                                                                                        0
Customer_Age                                                                                                                          0
Gender                                                                                                                                0
Dependent_count                                                                                                                       0
Education_Level                                                                                                                       0
Marital_Status                                                                                                                        0
Income_Category                                 

In [11]:
df['Customer_Age'].min(), df['Customer_Age'].max()


(26, 73)

In [13]:
df['Gender'].value_counts()


Gender
F    5358
M    4769
Name: count, dtype: int64

In [15]:
import numpy as np
a = np.arange(10, 21)
print(a)

[10 11 12 13 14 15 16 17 18 19 20]


In [17]:
b = np.random.randint(0, 11, size=(3, 4))
print(b)

[[4 7 6 1]
 [8 6 6 3]
 [3 7 1 6]]


In [19]:
print("Mean:", np.mean(b))
print("Max:", np.max(b))
print("Std Dev:", np.std(b))

Mean: 4.833333333333333
Max: 8
Std Dev: 2.266911751455907


In [21]:
import pandas as pd
df = pd.read_csv("BankChurners.csv")
df.head()

CLIENTNUM     Attrition_Flag  Customer_Age Gender  Dependent_count  \
0  768805383  Existing Customer            45      M                3   
1  818770008  Existing Customer            49      F                5   
2  713982108  Existing Customer            51      M                3   
3  769911858  Existing Customer            40      F                4   
4  709106358  Existing Customer            40      M                3   

  Education_Level Marital_Status Income_Category Card_Category  \
0     High School        Married     $60K - $80K          Blue   
1        Graduate         Single  Less than $40K          Blue   
2        Graduate        Married    $80K - $120K          Blue   
3     High School        Unknown  Less than $40K          Blue   
4      Uneducated        Married     $60K - $80K          Blue   

   Months_on_book  ...  Credit_Limit  Total_Revolving_Bal  Avg_Open_To_Buy  \
0              39  ...       12691.0                  777          11914.0   
1              44  ...        8256.0                  864           7392.0   
2              36  ...        3418.0                    0           3418.0   
3              34  ...        3313.0                 2517            796.0   
4              21  ...        4716.0                    0           4716.0   

   Total_Amt_Chng_Q4_Q1  Total_Trans_Amt  Total_Trans_Ct  Total_Ct_Chng_Q4_Q1  \
0                 1.335             1144              42                1.625   
1                 1.541             1291              33                3.714   
2                 2.594             1887              20                2.333   
3                 1.405             1171              20                2.333   
4                 2.175              816              28                2.500   

   Avg_Utilization_Ratio  \
0                  0.061   
1                  0.105   
2                  0.000   
3                  0.760   
4                  0.000   

   Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_1  \
0                                           0.000093                                                                                    
1                                           0.000057                                                                                    
2                                           0.000021                                                                                    
3                                           0.000134                                                                                    
4                                           0.000022                                                                                    

   Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_2  
0                                            0.99991                                                                                   
1                                            0.99994                                                                                   
2                                            0.99998                                                                                   
3                                            0.99987                                                                                   
4                                            0.99998                                                                                   

[5 rows x 23 columns]

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10127 entries, 0 to 10126
Data columns (total 23 columns):
 #   Column                                                                                                                              Non-Null Count  Dtype  
---  ------                                                                                                                              --------------  -----  
 0   CLIENTNUM                                                                                                                           10127 non-null  int64  
 1   Attrition_Flag                                                                                                                      10127 non-null  object 
 2   Customer_Age                                                                                                                        10127 non-null  int64  
 3   Gender                                                                           

In [25]:
df[df['Customer_Age'] > 50]


CLIENTNUM     Attrition_Flag  Customer_Age Gender  Dependent_count  \
2      713982108  Existing Customer            51      M                3   
6      810347208  Existing Customer            51      M                4   
11     710821833  Existing Customer            65      M                1   
12     710599683  Existing Customer            56      M                1   
14     712396908  Existing Customer            57      F                2   
...          ...                ...           ...    ...              ...   
10110  718225683  Existing Customer            56      M                1   
10117  712503408  Existing Customer            57      M                2   
10119  716893683  Attrited Customer            55      F                3   
10120  710841183  Existing Customer            54      M                1   
10121  713899383  Existing Customer            56      F                1   

      Education_Level Marital_Status Income_Category Card_Category  \
2            Graduate        Married    $80K - $120K          Blue   
6             Unknown        Married         $120K +          Gold   
11            Unknown        Married     $40K - $60K          Blue   
12            College         Single    $80K - $120K          Blue   
14           Graduate        Married  Less than $40K          Blue   
...               ...            ...             ...           ...   
10110        Graduate         Single    $80K - $120K        Silver   
10117        Graduate        Married    $80K - $120K          Blue   
10119      Uneducated         Single         Unknown          Blue   
10120     High School         Single     $60K - $80K          Blue   
10121        Graduate         Single  Less than $40K          Blue   

       Months_on_book  ...  Credit_Limit  Total_Revolving_Bal  \
2                  36  ...        3418.0                    0   
6                  46  ...       34516.0                 2264   
11                 54  ...        9095.0                 1587   
12                 36  ...       11751.0                    0   
14                 48  ...        2436.0                  680   
...               ...  ...           ...                  ...   
10110              49  ...       34516.0                 1091   
10117              40  ...       17925.0                 1909   
10119              47  ...       14657.0                 2517   
10120              34  ...       13940.0                 2109   
10121              50  ...        3688.0                  606   

       Avg_Open_To_Buy  Total_Amt_Chng_Q4_Q1  Total_Trans_Amt  Total_Trans_Ct  \
2               3418.0                 2.594             1887              20   
6              32252.0                 1.975             1330              31   
11              7508.0                 1.433             1314              26   
12             11751.0                 3.397             1539              17   
14              1756.0                 1.190             1570              29   
...                ...                   ...              ...             ...   
10110          33425.0                 0.640            15274             108   
10117          16016.0                 0.712            17498             111   
10119          12140.0                 0.166             6009              53   
10120          11831.0                 0.660            15577             114   
10121           3082.0                 0.570            14596             120   

       Total_Ct_Chng_Q4_Q1  Avg_Utilization_Ratio  \
2                    2.333                  0.000   
6                    0.722                  0.066   
11                   1.364                  0.174   
12                   3.250                  0.000   
14                   0.611                  0.279   
...                    ...                    ...   
10110                0.714                  0.032   
10117                0.820                  0.106   
10119     

In [27]:
even_array = np.arange(2, 21, 2)
print("Even numbers array:", even_array)

Even numbers array: [ 2  4  6  8 10 12 14 16 18 20]


In [29]:
data = np.random.randint(10, 100, size=(5, 5))
data[data > 50] = 50
print(data)

[[39 50 18 50 50]
 [50 50 50 50 23]
 [50 10 26 47 50]
 [50 50 50 50 50]
 [50 26 48 50 50]]


In [31]:
df['Income_Category'].nunique()


6

In [33]:
df['Card_Category'].value_counts()


Card_Category
Blue        9436
Silver       555
Gold         116
Platinum      20
Name: count, dtype: int64

In [38]:
list_data = [3, 6, 9, 12]
arr = np.array(list_data)
print(arr)

[ 3  6  9 12]


In [40]:
df[df['Customer_Age'] == 45]


CLIENTNUM     Attrition_Flag  Customer_Age Gender  Dependent_count  \
0      768805383  Existing Customer            45      M                3   
19     709327383  Existing Customer            45      F                2   
40     827111283  Existing Customer            45      M                3   
92     714107958  Existing Customer            45      M                1   
94     715550508  Existing Customer            45      F                3   
...          ...                ...           ...    ...              ...   
9978   768728508  Existing Customer            45      F                5   
10045  755305683  Existing Customer            45      M                5   
10079  715090008  Existing Customer            45      M                4   
10087  713768358  Existing Customer            45      M                4   
10088  709188108  Existing Customer            45      M                2   

      Education_Level Marital_Status Income_Category Card_Category  \
0         High School        Married     $60K - $80K          Blue   
19           Graduate        Married         Unknown          Blue   
40           Graduate         Single    $80K - $120K          Blue   
92           Graduate         Single     $40K - $60K          Blue   
94            Unknown        Married         Unknown          Blue   
...               ...            ...             ...           ...   
9978        Doctorate        Married  Less than $40K          Gold   
10045        Graduate        Married     $60K - $80K          Blue   
10079        Graduate         Single     $60K - $80K        Silver   
10087        Graduate         Single     $40K - $60K          Blue   
10088        Graduate         Single     $60K - $80K        Silver   

       Months_on_book  ...  Credit_Limit  Total_Revolving_Bal  \
0                  39  ...       12691.0                  777   
19                 37  ...       14470.0                 1157   
40                 41  ...       32426.0                  578   
92                 36  ...        6576.0                    0   
94                 28  ...        2535.0                 2440   
...               ...  ...           ...                  ...   
9978               39  ...       15987.0                 1096   
10045              38  ...        8983.0                    0   
10079              36  ...       28564.0                 2517   
10087              35  ...        7935.0                  888   
10088              33  ...       34516.0                 1529   

       Avg_Open_To_Buy  Total_Amt_Chng_Q4_Q1  Total_Trans_Amt  Total_Trans_Ct  \
0              11914.0                 1.335             1144              42   
19             13313.0                 0.966             1207              21   
40             31848.0                 1.042             1109              28   
92              6576.0                 0.579             1465              34   
94                95.0                 1.705             1312              20   
...                ...                   ...              ...             ...   
9978           14891.0                 0.625            14209             103   
10045           8983.0                 0.713            15163             124   
10079          26047.0                 0.711            14875             107   
10087           7047.0                 0.779            15380             122   
10088          32987.0                 0.609            13940             105   

       Total_Ct_Chng_Q4_Q1  Avg_Utilization_Ratio  \
0                    1.625                  0.061   
19                   0.909                  0.080   
40                   0.474                  0.018   
92                   0.619                  0.000   
94                   1.222                  0.963   
...                    ...                    ...   
9978                 0.776                  0.069   
10045                0.746                  0.000   
10079     

In [42]:
df[df['Card_Category'] == 'Platinum']


CLIENTNUM     Attrition_Flag  Customer_Age Gender  Dependent_count  \
443   788386908  Existing Customer            48      M                3   
650   779519058  Existing Customer            51      F                3   
3800  708654933  Attrited Customer            51      F                2   
8631  714754533  Existing Customer            51      M                0   
8863  714077583  Attrited Customer            43      M                3   
8897  709269708  Existing Customer            45      M                4   
9068  719071158  Attrited Customer            54      F                0   
9071  711364233  Existing Customer            41      M                4   
9078  823848183  Existing Customer            39      F                1   
9102  714190983  Attrited Customer            51      F                2   
9113  770848308  Existing Customer            45      M                2   
9127  713870958  Existing Customer            56      F                3   
9183  709319658  Attrited Customer            48      F                4   
9306  715017858  Existing Customer            44      M                2   
9319  771626283  Existing Customer            54      M                2   
9462  710362233  Existing Customer            48      M                3   
9550  709814883  Existing Customer            45      F                2   
9618  794494308  Existing Customer            42      M                3   
9828  709969758  Existing Customer            43      M                3   
9858  714949758  Existing Customer            51      F                3   

     Education_Level Marital_Status Income_Category Card_Category  \
443         Graduate        Unknown    $80K - $120K      Platinum   
650    Post-Graduate       Divorced         Unknown      Platinum   
3800       Doctorate        Married  Less than $40K      Platinum   
8631       Doctorate         Single         $120K +      Platinum   
8863   Post-Graduate        Married     $40K - $60K      Platinum   
8897        Graduate         Single         $120K +      Platinum   
9068        Graduate         Single         Unknown      Platinum   
9071         Unknown        Married     $60K - $80K      Platinum   
9078         Unknown         Single  Less than $40K      Platinum   
9102        Graduate         Single         Unknown      Platinum   
9113        Graduate        Married     $60K - $80K      Platinum   
9127      Uneducated         Single         Unknown      Platinum   
9183        Graduate         Single  Less than $40K      Platinum   
9306      Uneducated        Married         $120K +      Platinum   
9319   Post-Graduate        Married     $60K - $80K      Platinum   
9462         Unknown        Unknown    $80K - $120K      Platinum   
9550     High School         Single  Less than $40K      Platinum   
9618      Uneducated        Married         $120K +      Platinum   
9828        Graduate         Single     $60K - $80K      Platinum   
9858        Graduate         Single         Unknown      Platinum   

      Months_on_book  ...  Credit_Limit  Total_Revolving_Bal  Avg_Open_To_Buy  \
443               41  ...       34516.0                 1531          32985.0   
650               34  ...       34516.0                 1578          32938.0   
3800              42  ...       15987.0                  193          15794.0   
8631              44  ...       34516.0                 1925          32591.0   
8863              31  ...       23981.0                  593          23388.0   
8897              34  ...       34516.0                 1488          33028.0   
9068              38  ...       34516.0                    0          34516.0   
9071              26  ...       34516.0                 1559          32957.0   
9078              35  ...       15987.0                 1494          14493.0   
9102              32  ...       34516.0                  531          33985.0   
9113              31  ...       34516.0                 1308        

In [44]:
df['Marital_Status'].value_counts()['Married']


4687